### ISSUE TITLE
mabo doesn't work with bzip2 ?

### ISSUE THREAD

**Issue by wideglide** [ANSSI-FR/mabo#10]
using the example data http://data.ris.ripe.net/rrc01/2016.01/bview.20160101.0000.gz
I executed the `mabo prefixes` with three versions of the file
- plain bview.20160101.0000
- gzip bview.20160101.0000.gz
- bzip2 bview.20160101.0000.bz2

The first two work fine, using mabo on a bzip2 compressed file reports no prefixes?
I'm using Ubuntu 18.04 as the host OS.

**Comment by guedou** [comment]
Thnaks for reporting. PR #11 fixes this issue.
