### ISSUE TITLE
MRT parsing error: MRT dump is truncated: 1492578098 16/4 99

### ISSUE THREAD

**Issue by nagarjung** [ANSSI-FR/mabo#6]
Hi @guedou @nv-anssi ,  

I am unable to parse the BGP MRT update files collected from openbgpd router.
bgp command used to generate the update files ```dump all in "/tmp/all-in-%H%M" 300```

It parses few records, then fails with below error

```
MRT parsing error: MRT dump is truncated: 1492578098 16/4 99
MRT parsing error: MRT dump is truncated: 1492578098 16/4 99
MRT parsing error: MRT dump is truncated: 1492578098 16/4 99
MRT parsing error: MRT dump is truncated: 1492578098 16/4 99
```

I am able to parse the RIB files from the same router, problem is with update files.

But I am able to parse the mrt files from RIPE.

Thank you

**Comment by guedou** [comment]
Could you share the dump ? I am not familiar with OpenBGPD.

According to the documentation, you want to use `dump updates in "/tmp/updates-in-%H%M" 300`

**Comment by nagarjung** [comment]
[updates-in-1223.gz](https://github.com/ANSSI-FR/mabo/files/976078/updates-in-1223.gz)

Please find the attached file.
I have also tried with dump updates option. It does not work

**Comment by guedou** [comment]
It seems to work fine, see:
```
$ ./mabo dump updates-in-1223.gz
{"type":"update","timestamp":1493880788.0,"peer_as":4755.0,"peer_ip":"121.244.206.224","as_path":"4755 6453 7575 38022 55702","announce":["49.0.31.0/24"],"withdraw":[]}
[..]
MRT parsing error: MRT dump is truncated: 1493880791 16/4 138
```

The error only states that the file is broken. That could happen when the dump was not properly closed before copying it.

**Comment by nagarjung** [comment]
@guedou : But the router is able to successfully parse it.

**Comment by guedou** [comment]
You will need to provide more feedback to help me understand this behavior. For example, I will be helpful to know of the file was correctly closed. If the file and some MRT headers are corrupted, mabo won't try to parse them.

**Comment by nagarjung** [comment]
@guedou : It was a bug in OpenBSD which was fixed in latest release. Now files are properly generated and mabo is able to parse them.

Thanks
