### ISSUE TITLE
Negative AS Numbers (32Bit)

### ISSUE THREAD

**Issue by bhelm** [ANSSI-FR/mabo#7]
Large 32-Bit AS-Numbers are displayed negative, i.e. 4294901906 is displayed as -65390
those numbers may be invalid, but as they are contained in the RIPE RIS dump, they could be displayed correctly.

```
# mabo prefixes rrc00-bview.gz | grep '^-'
-65390 59.101.1.0/24
-65390 59.101.2.0/24
-65390 59.101.3.0/24
-65390 59.101.4.0/24
-65390 59.101.5.0/24
-65390 59.101.6.0/24
-65390 59.101.7.0/24
-65390 59.101.8.0/24
-65390 59.101.9.0/24
-65390 59.101.10.0/24
-65415 59.101.15.0/24
-65430 59.101.114.0/24
```
bgpdump as reference:
```
TABLE_DUMP2|06/23/17 08:00:01|B|203.119.76.5|4608|59.101.1.0/24|4608 24130 2764 4294901906|IGP
```

**Comment by ghost** [comment]
Thanks for reporting this issue. We were using the wrong printf conversion specifier (i instead of u).
